//! SeaORM Entity. Generated by sea-orm-codegen 0.4.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "ip")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Custom(\"inet\".to_owned())", unique)]
    pub address: String,
    pub first_seen_at: DateTime,
    pub last_seen_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ugc_revisions::Entity")]
    UgcRevisions,
}

impl Related<super::ugc_revisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UgcRevisions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
