//! SeaORM Entity. Generated by sea-orm-codegen 0.4.0

pub use super::ip::Entity as Ip;
pub use super::posts::Entity as Posts;
pub use super::sessions::Entity as Sessions;
pub use super::threads::Entity as Threads;
pub use super::ugc::Entity as Ugc;
pub use super::ugc_revisions::Entity as UgcRevisions;
pub use super::users::Entity as Users;
