//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "attachment_thumbnails")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub attachment_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub thumbnail_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::attachments::Entity",
        from = "Column::AttachmentId",
        to = "super::attachments::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Attachments2,
    #[sea_orm(
        belongs_to = "super::attachments::Entity",
        from = "Column::ThumbnailId",
        to = "super::attachments::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Attachments1,
}

impl ActiveModelBehavior for ActiveModel {}
