//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

pub mod prelude;

pub mod attachment_thumbnails;
pub mod attachments;
pub mod chat_messages;
pub mod chat_rooms;
pub mod forum_permissions;
pub mod forums;
pub mod groups;
pub mod ip;
pub mod permission_categories;
pub mod permission_collections;
pub mod permission_values;
pub mod permissions;
pub mod posts;
pub mod sessions;
pub mod threads;
pub mod ugc;
pub mod ugc_attachments;
pub mod ugc_deletions;
pub mod ugc_revisions;
pub mod user_2fa;
pub mod user_avatars;
pub mod user_groups;
pub mod user_name_history;
pub mod user_names;
pub mod users;
