//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

pub use super::attachment_thumbnails::Entity as AttachmentThumbnails;
pub use super::attachments::Entity as Attachments;
pub use super::ip::Entity as Ip;
pub use super::posts::Entity as Posts;
pub use super::sessions::Entity as Sessions;
pub use super::threads::Entity as Threads;
pub use super::ugc::Entity as Ugc;
pub use super::ugc_attachments::Entity as UgcAttachments;
pub use super::ugc_revisions::Entity as UgcRevisions;
pub use super::users::Entity as Users;
