//! SeaORM Entity. Generated by sea-orm-codegen 0.4.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "ugc")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ugc_revision_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ugc_revisions::Entity",
        from = "Column::UgcRevisionId",
        to = "super::ugc_revisions::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UgcRevisions,
    #[sea_orm(has_many = "super::posts::Entity")]
    Posts,
}

impl Related<super::ugc_revisions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UgcRevisions.def()
    }
}

impl Related<super::posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Posts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
