//! SeaORM Entity. Generated by sea-orm-codegen 0.4.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "xf_hb_chat_room")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub room_id: u32,
    pub title: String,
    pub description: String,
    pub display_order: u32,
    #[sea_orm(column_type = "Decimal(Some((16, 6)))", nullable)]
    pub motd_date: Option<Decimal>,
    pub motd_id: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
