//! SeaORM Entity. Generated by sea-orm-codegen 0.4.0

pub use super::chat_message::Entity as ChatMessage;
pub use super::chat_room::Entity as ChatRoom;
pub use super::user::Entity as User;
pub use super::user_ignored::Entity as UserIgnored;
